name: Auto PR and Merge

on:
  push:
    branches:
      - action

permissions:
  contents: write
  pull-requests: write

jobs:
  tests-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install pytest

      - run: pytest -v

  create-pr:
    needs: tests-pr
    runs-on: ubuntu-latest

    outputs:
      pr_number: ${{ steps.create_pr.outputs.pr_number }}

    steps:
      - name: Crear Pull Request
        id: create_pr
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              const pr = await github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: 'PR automático action -> main',
                head: 'action',
                base: 'main',
                body: 'Creado automáticamente desde GitHub Actions'
              });

              core.setOutput("pr_number", pr.data.number);

            } catch (error) {
              core.setFailed(error.message);
            }
  tests-mr:
    needs: create-pr
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install pytest

      - run: pytest -v

  merge-pr:
    needs: tests-mr
    runs-on: ubuntu-latest

    steps:
      - name: Merge Pull Request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = Number("${{ needs.create-pr.outputs.pr_number }}");

            if (!prNumber) {
              core.setFailed("No se encontró PR para mergear");
              return;
            }

            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              merge_method: 'squash'
            });
